version: '3.9'

services:
  nginx:
    platform: linux/x86_64
    image: nginx:1.13.8
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php8
      - php7

  php8:
    build:
      context: .docker/php8
      dockerfile: Dockerfile
    container_name: php8
    hostname: php8
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www
      - .docker/php8/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - .docker/php8/php.ini:/user/local/etc/php/php.ini
  
  php7:
    build:
      context: .docker/php7
      dockerfile: Dockerfile
    container_name: php7
    hostname: php7
    ports:
      - "9001:9000"
    volumes:
      - ./:/var/www
      - .docker/php7/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - .docker/php7/php.ini:/user/local/etc/php/php.ini
